workflows:
  flutter_android_debug:
    name: Flutter Android Debug
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter test
      - flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk

  ios_testflight:
    name: iOS TestFlight
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: dk.funhall.huskmig
    integrations:
      app_store_connect: "HuskMig-ASC-Key"
    scripts:
      - flutter pub get
      - name: CocoaPods
        script: cd ios && pod install
      - name: Apply provisioning profiles to Xcode project
        script: xcode-project use-profiles --project ios/Runner.xcodeproj --archive-method app-store
      - flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true